language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
  - composer self-update
  - composer install ${COMPOSER_FLAGS} --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpunit ${PHPUNIT_FLAGS}
